name = "emogen"
workers_dev = true
compatibility_date = "2023-02-24"
main = "build/worker/shim.mjs"
vars = { WORKERS_RS_VERSION = "0.0.16" }
routes = [
    "urem.uk/*",
    "*.urem.uk/*",
]

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "owari-shop"
preview_bucket_name = "owari-shop"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
